### ISSUE TITLE
Checkpoint/restart for macroscopic pml

### ISSUE THREAD

**Issue by RevathiJambunathan** [ECP-WarpX/artemis#40]
When using macroscopic maxwell with pml boundary conditions, the restarted simulation does not match with the simulation without restart when compared at the same timestep. This needs to be diagnosed and fixed.

**Comment by ajnonaka** [comment]
See PR #41 for demonstrations of successful and failing restarts for NON-LLG.

**Comment by ajnonaka** [comment]
Here is a non-LLG inputs file that fails a restart test.

`
# This is a E+B (use USE_LLG=FALSE, ie., no M field) simulation of a
# plane wave in a periodic domain

################################
####### GENERAL PARAMETERS ######
#################################
max_step = 10
amr.n_cell = 16 16 128
amr.max_grid_size = 32
amr.blocking_factor = 16
geometry.coord_sys   = 0
geometry.prob_lo     =  -16.e-6 -16.e-6 -128.e-6
geometry.prob_hi     =   16.e-6  16.e-6  128.e-6
boundary.field_lo = periodic periodic pml
boundary.field_hi = periodic periodic pml
amr.max_level = 0

#################################
############ NUMERICS ###########
#################################
warpx.verbose = 1
warpx.use_filter = 0
warpx.cfl = 0.9

algo.em_solver_medium = macroscopic # vacuum/macroscopic
algo.macroscopic_sigma_method = laxwendroff # laxwendroff or backwardeuler
macroscopic.sigma_function(x,y,z) = "0.0"
macroscopic.epsilon_function(x,y,z) = "8.8541878128e-12"
macroscopic.mu_function(x,y,z) = "1.25663706212e-06"

#################################
############ FIELDS #############
#################################

my_constants.pi = 3.14159265359
my_constants.L = 141.4213562373095e-6
my_constants.c = 299792458.
my_constants.wavelength = 64.e-6

warpx.E_ext_grid_init_style = parse_E_ext_grid_function
warpx.Ez_external_grid_function(x,y,z) = 0.
warpx.Ex_external_grid_function(x,y,z) = 0.
warpx.Ey_external_grid_function(x,y,z) = "1.e5*exp(-(z+64.e-6)**2/(L/4)**2)*cos(2*pi*(z+64.e-6)/wavelength)"

warpx.B_ext_grid_init_style = parse_B_ext_grid_function
warpx.Bx_external_grid_function(x,y,z)= "-1.e5*exp(-(z+64.e-6)**2/(L/4)**2)*cos(2*pi*(z+64.e-6)/wavelength)/c"
warpx.By_external_grid_function(x,y,z)= 0.
warpx.Bz_external_grid_function(x,y,z) = 0.

# Diagnostics
diagnostics.diags_names = plt chk
plt.intervals = 5
plt.fields_to_plot = Ex Ey Ez Bx By Bz
plt.diag_type = Full

chk.format = checkpoint
chk.intervals = 5
chk.diag_type = Full

#amr.restart = diags/chk00005
`

**Comment by ajnonaka** [comment]
Here is a non-LLG inputs file that does not restart properly

# This is a E+B (use USE_LLG=FALSE, ie., no M field) simulation of a
# plane wave in a periodic domain

################################
####### GENERAL PARAMETERS ######
#################################
max_step = 10
amr.n_cell = 16 16 128
amr.max_grid_size = 32
amr.blocking_factor = 16
geometry.coord_sys   = 0
geometry.prob_lo     =  -16.e-6 -16.e-6 -128.e-6
geometry.prob_hi     =   16.e-6  16.e-6  128.e-6
boundary.field_lo = periodic periodic pml
boundary.field_hi = periodic periodic pml
amr.max_level = 0

#################################
############ NUMERICS ###########
#################################
warpx.verbose = 1
warpx.use_filter = 0
warpx.cfl = 0.9

algo.em_solver_medium = macroscopic # vacuum/macroscopic
algo.macroscopic_sigma_method = laxwendroff # laxwendroff or backwardeuler
macroscopic.sigma_function(x,y,z) = "0.0"
macroscopic.epsilon_function(x,y,z) = "8.8541878128e-12"
macroscopic.mu_function(x,y,z) = "1.25663706212e-06"

#################################
############ FIELDS #############
#################################

my_constants.pi = 3.14159265359
my_constants.L = 141.4213562373095e-6
my_constants.c = 299792458.
my_constants.wavelength = 64.e-6

warpx.E_ext_grid_init_style = parse_E_ext_grid_function
warpx.Ez_external_grid_function(x,y,z) = 0.
warpx.Ex_external_grid_function(x,y,z) = 0.
warpx.Ey_external_grid_function(x,y,z) = "1.e5*exp(-(z+64.e-6)**2/(L/4)**2)*cos(2*pi*(z+64.e-6)/wavelength)"

warpx.B_ext_grid_init_style = parse_B_ext_grid_function
warpx.Bx_external_grid_function(x,y,z)= "-1.e5*exp(-(z+64.e-6)**2/(L/4)**2)*cos(2*pi*(z+64.e-6)/wavelength)/c"
warpx.By_external_grid_function(x,y,z)= 0.
warpx.Bz_external_grid_function(x,y,z) = 0.

# Diagnostics
diagnostics.diags_names = plt chk
plt.intervals = 5
plt.fields_to_plot = Ex Ey Ez Bx By Bz
plt.diag_type = Full

chk.format = checkpoint
chk.intervals = 5
chk.diag_type = Full

#amr.restart = diags/chk00005

**Comment by RevathiJambunathan** [comment]
This seems to be resolved. would be good to retest

**Comment by ajnonaka** [comment]
A more comprehensive set of restart tests need to be performed since much has changed over the months.
Pure EM containing PEC, PML, and Periodic, including macroscopic parameters
LLG also.

**Comment by ajnonaka** [comment]
Tested with pure EM and LLG with spatially-varying material properties, PML, and excitations.

See these examples:

./Examples/Tests/circuits/inputs_roger_pec_restarttest
./Examples/Tests/circuits/inputs_wave_restarttest
./Examples/Tests/Magnon_Photon/inputs_LLG_magnog_photon_restarttest
./Examples/Waveguide/inputs_3d_LLG_filter_restarttest
