### ISSUE TITLE
Make the parsing of Ms and other magnetic material properties consistent

### ISSUE THREAD

**Issue by jackieyao0114** [ECP-WarpX/artemis#60]
Currently, in both `MacroscopicEvolveHM.cpp` and `MacroscopicEvolveHM_2nd.cpp`, `mag_Ms_arr` is parsed directly to `M` field location (face centers), while the other related magnetic properties (`mag_alpha_arr`, `mag_gamma_arr`, `mag_exchange_arr`, `mag_anisotropy_arr`, let's call them "non-Ms" parameters) are parsed on cell centers and interpolated to the face centers by `CoarsenIO:Interp()`. 

This inconsistency is a killer for our simulations with exchange coupling turned-on, because the "non-Ms" parameters are halved  at the material interfaces, which introduces an artificial gradient of `M `and its exchange field. Once we hacked in a consistent case setup, this artificial effect disappeared.

**Comment by ajnonaka** [comment]
I suggest we change all magnetic materials to parsing on the fly so the material definitions of all magnetic material properties can be written consistently in an inputs file.

If timing shows that this slows down EvolveHM too much we may have to look at memory usage and consider storing the magnetic material properties in arrays of face-centered MultiFabs.  The tradeoff would be an extra 15 variables in memory (3 each of the 5 magnetic material properties).

**Comment by ajnonaka** [comment]
Fixed some time ago; Ms, alpha, gamma, exchange, and anisotropy are stored in arrays of MultiFabs directly on the face
